export const GET_POKEMON = "GET_POKEMON";
export const GET_POKEMON_LIST = "GET_POKEMON_LIST";
export const GET_40_POKEMON = "GET_40_POKEMON";
export const GET_TYPES = "GET_TYPES";
export const CREATE_POKEMON = "CREATE_POKEMON";
export const GET_POKEMON_BY_NAME = "GET_POKEMON_BY_NAME";
export const GET_POKEMON_BY_ID = "GET_POKEMON_BY_ID";
