export const GET_POKEMON_LIST = "GET_POKEMON_LIST";
export const GET_POKEMON_LIST_ERROR = "GET_POKEMON_LIST_ERROR";
export const GET_POKEMON_BY_NAME = "GET_POKEMON_BY_NAME";
export const GET_POKEMON_BY_NAME_ERROR = "GET_POKEMON_BY_NAME_ERROR";
export const GET_POKEMON_BY_ID = "GET_POKEMON_BY_ID";
export const GET_TYPES = "GET_TYPES";
export const GET_COUNT = "GET_COUNT";

export const SET_PAGE = "SET_PAGE";
export const SET_ORDER = "SET_ORDER";

export const FILTER_POKEMON = "FILTER_POKEMON";
export const FILTER_POKEMON_ERROR = "FILTER_POKEMON_ERROR";
export const FILTER_BY_ATTACK = "FILTER_BY_ATTACK";

export const CREATE_POKEMON = "CREATE_POKEMON";
export const CREATE_POKEMON_ERROR = "CREATE_POKEMON_ERROR";

export const CLEAR_POKEMON_LIST = "CLEAR_POKEMON_LIST";
export const CLEAR_POKEMON_SEARCH = "CLEAR_POKEMON_SEARCH";
export const CLEAR_POKEMON_DETAIL = "CLEAR_POKEMON_DETAIL";
export const CLEAR_POKEMON_CREATE = "CLEAR_POKEMON_CREATE";
export const CLEAR_ERROR = "CLEAR_ERROR";
